"""add whatsapp fields to users

Revision ID: 441b65776cdd
Revises: 77c51c97bc6c
Create Date: 2025-12-27 02:42:00.506091+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441b65776cdd'
down_revision: Union[str, None] = '77c51c97bc6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cash_entries', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.add_column(
        "users",
        sa.Column(
            "phone_e164",
            sa.String(length=20),
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "whatsapp_opt_in",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column(
        "users",
        "whatsapp_opt_in",
        server_default=None,
    )
    op.create_index(op.f('ix_users_phone_e164'), 'users', ['phone_e164'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_e164'), table_name='users')
    op.drop_column('users', 'whatsapp_opt_in')
    op.drop_column('users', 'phone_e164')
    op.alter_column('cash_entries', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
