"""add sort_order to services

Revision ID: 48723455eec9
Revises: a25244c70275
Create Date: 2025-12-28 22:43:33.588808+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48723455eec9'
down_revision: Union[str, None] = 'a25244c70275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=True))
    op.create_index(op.f('ix_services_sort_order'), 'services', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_sort_order'), table_name='services')
    op.drop_column('services', 'sort_order')
    # ### end Alembic commands ###
