"""add cancel_reason to appointments

Revision ID: 75237cb7a1bd
Revises: 4fe81c1f786d
Create Date: 2025-12-27 23:32:15.023775+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75237cb7a1bd'
down_revision: Union[str, None] = '4fe81c1f786d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('cancel_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_site_social_links_sort_order'), 'site_social_links', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_social_links_sort_order'), table_name='site_social_links')
    op.drop_column('appointments', 'cancel_reason')
    # ### end Alembic commands ###
