"""add position and sort_order to users

Revision ID: 821c14973c6b
Revises: 48723455eec9
Create Date: 2025-12-29 02:02:17.368807+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '821c14973c6b'
down_revision: Union[str, None] = '48723455eec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sort_order', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('users', sa.Column('position', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_users_sort_order'), 'users', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sort_order'), table_name='users')
    op.drop_column('users', 'position')
    op.drop_column('users', 'sort_order')
    # ### end Alembic commands ###
