"""add is_popular and is_deal to services

Revision ID: 98a753db4da8
Revises: 821c14973c6b
Create Date: 2025-12-29 03:16:00.285059+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98a753db4da8'
down_revision: Union[str, None] = '821c14973c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('is_popular', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('services', sa.Column('is_deal', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'is_deal')
    op.drop_column('services', 'is_popular')
    # ### end Alembic commands ###
