"""add secondary_title to slides

Revision ID: a25244c70275
Revises: 75237cb7a1bd
Create Date: 2025-12-28 15:45:27.391253+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a25244c70275'
down_revision: Union[str, None] = '75237cb7a1bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slides', sa.Column('secondary_title', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slides', 'secondary_title')
    # ### end Alembic commands ###
