"""init tables

Revision ID: ad4bc2192536
Revises: 
Create Date: 2025-12-26 19:54:07.626382+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4bc2192536'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('break_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN', name='weekday'), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_break_blocks_weekday'), 'break_blocks', ['weekday'], unique=False)
    op.create_index('ix_break_weekday_time', 'break_blocks', ['weekday', 'start_time', 'end_time'], unique=False)
    op.create_table('business_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN', name='weekday'), nullable=False),
    sa.Column('open_time', sa.String(length=5), nullable=False),
    sa.Column('close_time', sa.String(length=5), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_hours_weekday'), 'business_hours', ['weekday'], unique=False)
    op.create_index('ux_business_hours_weekday', 'business_hours', ['weekday'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_business_hours_weekday', table_name='business_hours')
    op.drop_index(op.f('ix_business_hours_weekday'), table_name='business_hours')
    op.drop_table('business_hours')
    op.drop_index('ix_break_weekday_time', table_name='break_blocks')
    op.drop_index(op.f('ix_break_blocks_weekday'), table_name='break_blocks')
    op.drop_table('break_blocks')
    # ### end Alembic commands ###
