"""services description nullable

Revision ID: e1e7b3f7d1c2
Revises: ad4bc2192536
Create Date: 2025-12-26 19:57:06.597150+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e7b3f7d1c2'
down_revision: Union[str, None] = 'ad4bc2192536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
